//import './globals.css';
//export default function RootLayout({ children }) {
//  return (
//    <html lang="en">
//      <body>{children}</body>
//    </html>
//  )
//}

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 1. Configuración de fuentes (Extraída del código TSX)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 2. Metadatos de la página (Extraída del código TSX)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 3. Componente RootLayout (Estructura JS con clases TSX)
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Las clases de fuente se aplican al body para usar las variables CSS */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}